name: simple_todo_list
description: "simple todo list project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  hooks_riverpod: ^2.5.1
  flutter_hooks: ^0.20.5
  json_annotation: ^4.6.0
  freezed_annotation: ^2.4.0
  uuid: ^4.4.2
  shared_preferences: ^2.2.3
  backdrop: ^0.9.1
  url_launcher: ^6.0.20
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  share_plus: ^9.0.0
  file_picker: ^8.0.6
  carbon_icons: ^0.0.1+2
  animations: ^2.0.11
  fluid_dialog: ^2.0.0
  go_router: ^14.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.2.0
  freezed: ^2.4.0
  json_serializable: ^6.1.0
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/rubik/Rubik-Regular.ttf
        - asset: assets/fonts/rubik/Rubik-Medium.ttf
          weight: 500
        - asset: assets/fonts/rubik/Rubik-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/rubik/Rubik-Bold.ttf
          weight: 700
        - asset: assets/fonts/rubik/Rubik-Light.ttf
          weight: 300